services:
  owncloud:
    container_name: owncloud-container
    image: owncloud:latest
    ports:
    - 8080:80
    networks:
      - owncloud-network
    environment:
#      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owndb
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud-password
      - OWNCLOUD_DB_HOST=mysql-container
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin-password
      - OWNCLOUD_MYSQL_UTF8MB4=true
#      - OWNCLOUD_REDIS_ENABLED=true
#      - OWNCLOUD_REDIS_HOST=redis
    depends_on:
      - mysql
  
  mysql:
    container_name: mysql-container
    image: mysql:8.0.29
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=owndb
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud-password
    networks:
      - owncloud-network

networks:
  owncloud-network:
    name: owncloud-network